name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: Configure Docker
      run: gcloud auth configure-docker
      
    - name: Build and push Docker image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/ema-sharpe
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ema-sharpe \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/ema-sharpe \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --port 8080 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10
          
    - name: Get service URL
      run: |
        SERVICE_URL=$(gcloud run services describe ema-sharpe --platform managed --region us-central1 --format 'value(status.url)')
        echo "Service deployed at: $SERVICE_URL"
        echo "::set-output name=service_url::$SERVICE_URL"
